// src/types/alert.types.ts

import { User } from './auth.types';
import { Deal } from './deal.types';
import { Portfolio } from './portfolio.types';

export interface RelatedEntities {
  startup_ids?: (string | Deal)[]; // Can be ObjectId string or populated Deal object
  portfolio_ids?: (string | Portfolio)[]; // Can be ObjectId string or populated Portfolio object
}

export interface Alert {
  id: string; // Mongoose _id
  user_id: string | User; // Can be ObjectId string or populated User object
  type:
    | 'competitive_threat'
    | 'market_shift'
    | 'portfolio_anomaly'
    | 'funding_round'
    | 'regulatory_change'
    | 'custom';
  title: string;
  description: string;
  severity: 'low' | 'medium' | 'high' | 'critical';
  status: 'unread' | 'read' | 'archived';
  related_entities: RelatedEntities;
  data: any; // Flexible field for alert-specific data
  action_required: boolean;
  action_url?: string;
  triggered_at: Date;
  read_at?: Date;
  expires_at?: Date;
  created_at: Date;
}

// Payload for creating a new alert (if applicable, typically generated by backend)
export type CreateAlertPayload = Omit<Alert, 'id' | 'created_at' | 'triggered_at' | 'status'>;

// Payload for updating an existing alert (e.g., changing status)
export type UpdateAlertPayload = Partial<Pick<Alert, 'status' | 'read_at'>>;
