// src/types/scoring.types.ts

import { Deal } from './deal.types';
import { User } from './auth.types';

export interface ScoreBreakdown {
  market_score: number;
  traction_score: number;
  team_score: number;
  financial_score: number;
  product_score?: number;
  competitive_score?: number;
}

export interface DetailedAnalysis {
  market_size_estimate?: number;
  growth_potential: 'low' | 'medium' | 'high' | 'very-high';
  risk_level: 'low' | 'medium' | 'high' | 'very-high';
  recommendation: 'pass' | 'watch' | 'consider' | 'strong-consider' | 'pursue';
  strengths: string[];
  weaknesses: string[];
  key_risks: string[];
  opportunities: string[];
}

export interface ScoringWeights {
  market_weight: number;
  traction_weight: number;
  team_weight: number;
  financial_weight: number;
}

export interface ScoringParameters {
  weights_used: ScoringWeights;
  features_used: string[];
  algorithm: 'random-forest' | 'gradient-boost' | 'neural-network' | 'ensemble';
}

export interface Score {
  id: string; // Mongoose _id
  startup_id: string | Deal; // Can be ObjectId string or populated Startup object
  user_id?: string | User; // User who requested the score
  investment_fit_score: number;
  breakdown: ScoreBreakdown;
  detailed_analysis: DetailedAnalysis;
  confidence: number;
  ml_model_version: string;
  scoring_parameters: ScoringParameters;
  scored_at: Date;
  expires_at?: Date;
  is_latest: boolean;
  notes?: string;
  created_at: Date;
  score_grade?: string; // Virtual field
}

// Payload for creating a new score (if applicable, typically generated by backend)
export type CreateScorePayload = Omit<Score, 'id' | 'created_at' | 'score_grade' | 'expires_at' | 'is_latest'>;

export interface ScoringHistoryItem {
  id: string;
  score: number;
  evaluatedAt: Date;
  // Potentially include more details like who scored it, full Score object, etc.
}
